### ISSUE TITLE
Demonstration online CHIMLE

### ISSUE THREAD

**Issue by Ivan29B** [niopeng/CHIMLE#2]
Will a demo be released on Google Colab or Huggingface, Replicate? Thanks

**Comment by niopeng** [comment]
Yes, we will release a demo later. Please stay tuned.

**Comment by niopeng** [comment]
The demo code has been released on [Colab](https://colab.research.google.com/github/niopeng/CHIMLE/blob/main/Demo/CHIMLE_demo.ipynb).
