### ISSUE TITLE
Questions about super-resolution task. 

### ISSUE THREAD

**Issue by zsy950116** [niopeng/CHIMLE#3]
Thanks for your great work. Here's a question about super-resolution task. I downloaded the butterfly datasets (n02279982) and try to generate the SR results under 16x factor. I don't know how you divided the training and testing datasets, so i tested on the whole datasets. However, i didn't get the similar results with yours, some samples showcase significant errors.  All the conditions are following your file, except for the down-sampling strategy. Is that possible that the down-sampling method can cause these errors? Looking forward to your reply.

**Comment by niopeng** [comment]
Hi,

Thank you for your interest. 

Yes, the downsampling strategy may effect the model performance. We used bicubic downsampling from PIL -- the important part is to use an **antialiasing** downsampling method. Also, there are many packages that fail to implement the antialiasing part properly, so we would recommend using PIL.

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。

**Comment by zsy950116** [comment]
Thanks for your response. Problem solved.
